### ISSUE TITLE
NoMethodError in Users::OmniauthCallbacksController#facebook

### ISSUE THREAD

**Issue by danlorry** [diowa/icare#46]
Error:

undefined method `[]' for nil:NilClass

Extracted source (around line #49):
             
      # Adds context (url, user agent, framework version, controller, etc)
      add_builder do |notice, request|
        context = notice[:context]

        context[:url] = request.url
        context[:userAgent] = request.user_agent

**Comment by tagliala** [comment]
@danlorry I'm aware of this issue and I'm working to update icare to work with facebook API 2.6. It's not a straightforward issue, a lot of things changed

**Comment by tagliala** [comment]
This should be working now in 0.38.0
